"""FastAPI surface for the Streamlens dashboards and proposals.

Four kinds of route:

    /api/query/{name}   deterministic reads from the named registry, used by
                        every chart. No model in the path.
    /api/dashboards     the dashboards the agent builds, and the data behind
                        each panel.
    /api/proposals      the one-sheets the agent writes for filmmakers: the
                        prose, the charts each one owns, and its stills.
    /mcp/*              the same tools spoken as MCP, for our agent and for
                        any other MCP client.

A panel's data is never generated by the model. The model writes the SQL and
picks the columns once, at authoring time; from then on the panel replays
that stored query directly against ClickHouse. A proposal's charts work the
same way, on the proposal's own copy of the query rather than a dashboard's.
"""

from __future__ import annotations

import logging
import os
from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI, HTTPException, Query as Q
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response, StreamingResponse
from pydantic import BaseModel

from streamlens.api import queries
from streamlens.dashboards import store
from streamlens.mcp.dashboards import server as dashboard_mcp
from streamlens.mcp.proposals import server as proposal_mcp
from streamlens.services.clickhouse.catalog import (
    database_payload,
    read_catalog,
    read_table_preview,
)
from streamlens.services.clickhouse.clickhouse_services import shared_client
from streamlens.services.clickhouse.sources import read_sources

log = logging.getLogger(__name__)

# Mounted below. Each session manager has to be started by a lifespan, and a
# mounted sub-app's own lifespan is never run, so the parent runs both.
_mcp_app = dashboard_mcp.streamable_http_app()
_proposal_mcp_app = proposal_mcp.streamable_http_app()


@asynccontextmanager
async def lifespan(_: FastAPI):
    from streamlens.dashboards.store import ensure_schema
    from streamlens.proposals.store import ensure_schema as ensure_proposal_schema

    try:
        ensure_schema()
        ensure_proposal_schema()
    except Exception:
        # A warehouse that is briefly unreachable should not stop the API
        # from serving; the dashboard routes will report it themselves.
        log.exception("could not ensure the dashboard and proposal schemas")

    async with _mcp_app.router.lifespan_context(_mcp_app):
        async with _proposal_mcp_app.router.lifespan_context(_proposal_mcp_app):
            yield


app = FastAPI(
    title="Streamlens API",
    version="0.1.0",
    description="Read-only analytics over ClickHouse Cloud for the Streamlens dashboards.",
    lifespan=lifespan,
)

app.mount("/mcp/dashboards", _mcp_app)
app.mount("/mcp/proposals", _proposal_mcp_app)

# The Next.js app is the only intended caller. Overridable so a deployed
# frontend origin can be added without a code change.
app.add_middleware(
    CORSMiddleware,
    allow_origins=os.environ.get(
        "STREAMLENS_CORS_ORIGINS", "http://localhost:3000"
    ).split(","),
    allow_methods=["*"],
    allow_headers=["*"],
)

def client():
    return shared_client()


@app.get("/health")
def health() -> dict[str, Any]:
    try:
        version = client().command("SELECT version()")
        return {"ok": True, "clickhouse": version}
    except Exception as exc:
        log.exception("health check failed")
        raise HTTPException(503, f"clickhouse unreachable: {exc}") from exc


@app.get("/api/warehouse")
def warehouse() -> dict[str, Any]:
    """The instance as it stands: ingestion sources, databases, tables.

    Read live on every call. The UI that draws the source rail owns no list
    of its own, so a new pipe shows up without a deploy.
    """
    from streamlens.config import clickhouse_cloud_settings

    try:
        version, databases = read_catalog()
        sources = read_sources(databases)
    except Exception as exc:
        log.exception("warehouse read failed")
        raise HTTPException(502, f"warehouse unreachable: {exc}") from exc

    return {
        "service": {
            "name": clickhouse_cloud_settings().service_name,
            "version": version,
        },
        "sources": sources,
        "databases": database_payload(databases),
    }


@app.get("/api/table/{database}/{table}")
def table_preview(
    database: str,
    table: str,
    limit: int = Q(200, ge=1, le=1000),
) -> dict[str, Any]:
    """One table opened for reading: its columns and its first rows."""
    try:
        return read_table_preview(database, table, limit)
    except LookupError as exc:
        raise HTTPException(404, str(exc)) from None
    except Exception as exc:
        log.exception("preview %s.%s failed", database, table)
        raise HTTPException(500, f"preview failed: {exc}") from exc


# ----------------------------------------------------------- dashboards


class DashboardBody(BaseModel):
    title: str
    description: str = ""


@app.get("/api/dashboards")
def dashboards() -> dict[str, Any]:
    try:
        return {"dashboards": store.list_dashboards()}
    except Exception as exc:
        log.exception("listing dashboards failed")
        raise HTTPException(502, str(exc)) from exc


@app.post("/api/dashboards")
def create_dashboard(body: DashboardBody) -> dict[str, Any]:
    try:
        return {"id": store.create_dashboard(body.title, body.description)}
    except store.DashboardError as exc:
        raise HTTPException(400, str(exc)) from None


@app.get("/api/dashboards/{dashboard_id}")
def dashboard(dashboard_id: str) -> dict[str, Any]:
    try:
        return store.get_dashboard(dashboard_id).to_dict()
    except store.DashboardError as exc:
        raise HTTPException(404, str(exc)) from None


@app.delete("/api/dashboards/{dashboard_id}")
def remove_dashboard(dashboard_id: str) -> dict[str, Any]:
    try:
        return {"deleted_panels": store.delete_dashboard(dashboard_id)}
    except store.DashboardError as exc:
        raise HTTPException(404, str(exc)) from None


@app.get("/api/dashboards/{dashboard_id}/panels/{panel_id}/data")
def panel_data(dashboard_id: str, panel_id: str) -> dict[str, Any]:
    """The rows behind one panel, by replaying its stored query.

    The query is whatever was validated when the panel was saved, so this
    route is a straight read — nothing here consults the model.
    """
    try:
        dash = store.get_dashboard(dashboard_id)
    except store.DashboardError as exc:
        raise HTTPException(404, str(exc)) from None

    panel = next((p for p in dash.panels if p.id == panel_id), None)
    if panel is None:
        raise HTTPException(404, f"no panel {panel_id!r} on {dashboard_id!r}")

    try:
        result = store.run_panel_query(panel.query)
    except store.DashboardError as exc:
        raise HTTPException(502, str(exc)) from None

    return {
        "panel": panel.to_dict(),
        "columns": result["columns"],
        "types": result["types"],
        "rows": result["rows"],
    }


# ------------------------------------------------------------ proposals


class ArchetypeBody(BaseModel):
    name: str
    note: str = ""


class ProposalBody(BaseModel):
    """A proposal as prose. Deliberately no SQL anywhere in this body —
    charts arrive by adopting a panel, which copies a definition that was
    already validated."""

    title: str
    genre: str
    kicker: str = ""
    budget: str = ""
    hook: str = ""
    logline: str = ""
    connection: str = ""
    theme: str = ""
    market: str = ""
    archetypes: list[ArchetypeBody] = []
    source_dashboard_id: str = ""
    source_dashboard_title: str = ""


@app.get("/api/proposals")
def proposals() -> dict[str, Any]:
    from streamlens.proposals import store as proposal_store

    try:
        return {"proposals": proposal_store.list_proposals()}
    except Exception as exc:
        log.exception("listing proposals failed")
        raise HTTPException(502, str(exc)) from exc


@app.post("/api/proposals")
def create_proposal(body: ProposalBody) -> dict[str, Any]:
    from streamlens.proposals import store as proposal_store

    result = proposal_store.create_proposal(body.model_dump())
    if not result.get("ok"):
        raise HTTPException(400, "; ".join(result.get("problems", [])))
    return {"id": result["proposal_id"]}


@app.get("/api/proposals/{proposal_id}")
def proposal(proposal_id: str) -> dict[str, Any]:
    from streamlens.proposals import store as proposal_store

    try:
        return proposal_store.get_proposal(proposal_id).to_dict()
    except proposal_store.ProposalError as exc:
        raise HTTPException(404, str(exc)) from None


@app.delete("/api/proposals/{proposal_id}")
def remove_proposal(proposal_id: str) -> dict[str, Any]:
    from streamlens.proposals import store as proposal_store

    try:
        return proposal_store.delete_proposal(proposal_id)
    except proposal_store.ProposalError as exc:
        raise HTTPException(404, str(exc)) from None


@app.get("/api/proposals/{proposal_id}/panels/{panel_id}")
def proposal_panel_data(proposal_id: str, panel_id: str) -> dict[str, Any]:
    """The rows behind one chart on a proposal.

    The proposal's own copy of the query, replayed through the same
    read-only gate a dashboard panel uses. Nothing here consults the
    dashboard it was adopted from — that is the whole point of owning it.
    """
    from streamlens.proposals import store as proposal_store

    try:
        return proposal_store.run_proposal_panel(proposal_id, panel_id)
    except proposal_store.ProposalError as exc:
        raise HTTPException(404, str(exc)) from None
    except store.DashboardError as exc:
        # The stored query no longer runs — a table dropped, a TTL expired,
        # a schema change. One panel fails; the report keeps rendering.
        raise HTTPException(502, str(exc)) from None


@app.get("/api/proposals/{proposal_id}/stills/{still_id}")
def proposal_still(proposal_id: str, still_id: str) -> Response:
    """One generated still, streamed out of the bucket.

    The bucket enforces public access prevention and nothing ever mints a
    signed URL, so this is the only route to the bytes — which is what
    makes a link unable to outlive the proposal that owns it. The object at
    a given id never changes, hence immutable; private, because the
    proposal is.

    A row whose object has gone is a 404, not a 500: the report's `onError`
    falls back to the tone gradient either way.
    """
    from streamlens.proposals import stills as proposal_stills
    from streamlens.proposals import store as proposal_store
    from streamlens.services.gcp.gcp_services import StorageError

    try:
        data, content_type = proposal_stills.read_still(proposal_id, still_id)
    except proposal_store.ProposalError as exc:
        raise HTTPException(404, str(exc)) from None
    except StorageError as exc:
        log.warning("still %s/%s is missing: %s", proposal_id, still_id, exc)
        raise HTTPException(404, "still not found") from None

    return Response(
        content=data,
        media_type=content_type,
        headers={"Cache-Control": "private, max-age=31536000, immutable"},
    )


class ChatBody(BaseModel):
    message: str
    session_id: str

    # What the user is looking at, so "make that one weekly" has a referent.
    # The browser sends the open tab; without it the agent has to guess which
    # of several dashboards a pronoun meant, and it guesses wrong.
    focus_kind: str = ""
    focus_id: str = ""


@app.post("/api/chat")
async def chat(body: ChatBody) -> StreamingResponse:
    """One turn with the analyst, streamed as server-sent events."""
    from streamlens.api.chat import stream_turn

    if not body.message.strip():
        raise HTTPException(400, "message is required")

    return StreamingResponse(
        stream_turn(
            body.message,
            body.session_id,
            focus_kind=body.focus_kind,
            focus_id=body.focus_id,
        ),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


@app.get("/api/queries")
def list_queries() -> dict[str, Any]:
    return {
        "queries": [
            {"name": n, "summary": queries.get(n).summary,
             "params": sorted(queries.get(n).defaults)}
            for n in queries.names()
        ]
    }


@app.get("/api/query/{name}")
def run_query(
    name: str,
    title: str | None = None,
    week: str | None = None,
    category: str | None = None,
    market: str | None = None,
    kind: str | None = None,
    search: str | None = Q(None, max_length=120),
    limit: int | None = Q(None, ge=1, le=5000),
    min_channels: int | None = Q(None, ge=0),
    min_weeks: int | None = Q(None, ge=0),
    months: int | None = Q(None, ge=1, le=240),
) -> dict[str, Any]:
    try:
        q = queries.get(name)
    except KeyError:
        raise HTTPException(404, f"unknown query {name!r}") from None

    supplied = {
        "title": title, "week": week, "category": category,
        "market": market, "kind": kind, "search": search,
        "limit": limit, "min_channels": min_channels,
        "min_weeks": min_weeks, "months": months,
    }
    params = dict(q.defaults)
    for key, value in supplied.items():
        if value is not None and key in params:
            params[key] = value

    try:
        result = client().query(q.sql, parameters=params)
    except Exception as exc:
        log.exception("query %s failed", name)
        raise HTTPException(500, f"query failed: {exc}") from exc

    return {
        "name": name,
        "columns": result.column_names,
        "rows": [
            dict(zip(result.column_names, row)) for row in result.result_rows
        ],
        "row_count": len(result.result_rows),
    }


@app.get("/api/agent/brief")
def agent_brief(title: str, evidence: bool = False) -> dict[str, Any]:
    """Gemini's read on one title, over a fixed retrieval pipeline.

    Every figure the model sees came from the same named queries that back
    the dashboards, so the brief and the charts cannot disagree.
    """
    from streamlens.agents.greenlight import write_brief

    if not title.strip():
        raise HTTPException(400, "title is required")

    try:
        brief = write_brief(client(), title)
    except Exception as exc:
        log.exception("brief failed for %s", title)
        raise HTTPException(502, f"brief failed: {exc}") from exc

    body: dict[str, Any] = {"title": brief.title, "brief": brief.text}
    if evidence:
        body["evidence"] = brief.evidence
    return body


@app.get("/api/title/artwork")
def title_artwork(title: str) -> dict[str, Any]:
    """TMDB poster and backdrop for a title. Token stays on this process."""
    from streamlens.services.tmdb import title_artwork as lookup

    if not title.strip():
        raise HTTPException(400, "title is required")
    try:
        return lookup(title)
    except Exception as exc:
        log.exception("tmdb artwork failed")
        raise HTTPException(502, f"tmdb unreachable: {exc}") from exc
